{% set version = "0.30.1" %}
{% set sha256 = "323b96d2e90d2cebe62d4942933fc29807bdf0d2728236d55155b3b21615ef4a" %}

package:
  name: pweave
  version: {{ version }}

source:
  fn: Pweave-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pweave/Pweave-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pweave = pweave.scripts:weave
    - ptangle = pweave.scripts:tangle
    - pypublish = pweave.scripts:publish
    - pweave-convert = pweave.scripts:convert

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - markdown
    - pygments
    - ipykernel
    - ipython
    - nbformat
    - nbconvert
    - jupyter_client

test:
  imports:
    - pweave
    - pweave.formatters
    - pweave.themes
    - pweave.formatters
    - pweave.processors
    - pweave.bokeh

  commands:
    - pweave --help
    - ptangle --help
    - pypublish --help
    - pweave-convert --help

about:
  home: http://mpastell.com/pweave
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Scientific reports with embedded python computations with reST, LaTeX or markdown'
  description: |
    Pweave is a scientific report generator and a literate programming
    tool for Python. It can capture the results and plots from data
    analysis and works well with numpy, scipy and matplotlib.
  doc_url: http://mpastell.com/pweave
  dev_url: https://github.com/mpastell/Pweave

extra:
  recipe-maintainers:
    - mpastell
