travis:
  secure:
    BINSTAR_TOKEN: JtdO2p8aEmiauGuoG9WRz+mii6bTa2u71oUN8j32AkaaHvfxZYchDkDmSbTg56wjfKRup0hT3f4o87nHbnnnHf0Q3uxAVZ8dszYbN5deB68qqAlFKGb9WaGGrVdm459D/66acCao1qzTHTv3EHtJSJnrGbnxCJpTj3meQaCWNAxT+XKy1ghwDe/0nYvq7HS4lyw+Kpu7pYqoYZEShGkMmGbbz1/K7W7QJZTZXkhauGAPu2mzw/r1pZKpfatFRxCRNRZhN/psWAZ5Hli+K+kD54rsQONZcddXAjUxK+oB6CfjCKG/46VKs1mxWz4kwTp7Scq/8hsgDNJv2J+7RLLDECD4I6TiJtfrvDQT183CuKOi3mTQ3MbTy7w+5jHho6/OqHiAs/dPV5miBuMxVKG7UT2RQBLlkvNNUbE/IqsZbqQhejS7/wEzv7PcO06TKU8BD2xlb5+JTQY60vmxhTJGreQe46yLebVVDOf5MTtN1IPe4ozdt70Cn7xUBT5WbkVeBeL0CWVUDT+IpVqSKtoj5jg2FU5d+aSixbeb/3pl7jjBOcm9bN5sOrDqlpiYzjddl/K38t2NbsApfYQ5jUk+xEaNeVvnUND5xNExbFKl1QmgsPEblvj1Bw061pk8Am7e4oJWFjAA2E1EbYZlyBfO3UJw9Ma54gD8uIdV+cez1y4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
