travis:
  secure:
    BINSTAR_TOKEN: CPqF5DebG5KxZVkb4WisxAZDBQiSFrdjJFduw+F2XYyZYe6ycviAKX+k2secmioJB5P9eZ28sKu4c8YgZzZl1xWs/DYpYp2DJUsOa8bNt+5Y/js8XonB8OPWlmbKzr1RK9tOH6Qur+4myUJMfi1PyzQCq+IP+D3+Ufx0NDbLRk6JVHXNl6ql37iidhvnhPOJHxt7qLhnOAEvxsSps/qysifTpSZDAetDvtVG0psm8g7vlCHhJ7MKAjMY8Gpe7yKTCdMCmrmUHq074JngpbFn0Yl8m3TGeS/kr4O4uOmVp+OLK1pcNh4YYGOZU+8GvoonwybgoWge+XPqH1YZVrSEq3svNulDpP0pjYbZAaTQQQ3HEtvW0S/6cWGdoQLWgnHsv5UAaooxwszs7ArE/XNApj5JKRUDVISjBnL7RyD2jBHD/TdGVHePAs7XREpOnwGoJFfB+42Bl/l0waWBwFtgOZbVJiJYDuk19yxs8xiicsfXa7U/1lUja4sB0CBcVYSFoSZb3wQH0t947IrEL4K4BnEg3MJS66m3fo83w8kGbt5u4UZmmnr0gI267FmtwygLYrLv6KQFzMGGDEYFLAxwxyri2H+ROQA3rEivNFjG7Qwlvgh9I/8r9mechLzMzxVn1pHfFnE2nMZaJH3FShqnjSg4ftTjez29H5yv3qYs1zE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
